export type Lang = "en" | "hi";

export const dict: Record<Lang, Record<string, string>> = {
  en: {
    "app.name": "PashuMarket",
    "nav.sell": "Sell Cattle",
    "nav.dashboard": "Dashboard",
    "nav.search": "Search cattle, breed, or location",
    "hero.title": "Buy & Sell Cattle with Trust",
    "hero.subtitle": "Video-first marketplace connecting farmers directly",
    "browse.title": "Popular cattle categories",
    "browse.label": "Browse by type",
    "listings.featured": "Featured listings",
    "listings.search": "Search results",
    "listings.results_for": 'Results for "{query}"',
    "listings.category": "{category} listings",
    "listings.recent": "Recent cattle ready to explore",
    "listings.description": "These sample cards help shape the first marketplace experience. Replace them with live seller listings once the data layer is ready.",
    "listings.empty": "No listings found",
    "listings.empty_hint": "Try a different search or browse categories above.",
    "card.view_details": "View Details",
    "card.featured": "Featured",
    "card.sold": "Sold",
    "detail.back": "Back to listings",
    "detail.about": "About this animal",
    "detail.price": "Price",
    "detail.age": "Age",
    "detail.milk_yield": "Milk yield",
    "detail.vaccination": "Vaccination",
    "detail.call_now": "Call Now",
    "detail.whatsapp": "WhatsApp Inquiry",
    "detail.share": "Share on WhatsApp",
    "detail.verified_seller": "Verified Seller",
    "detail.seller": "Seller",
    "detail.views": "views",
    "detail.interested": "interested",
    "dashboard.subtitle": "Manage your cattle listings — edit details, mark as sold, or remove them.",
    "dashboard.empty": "No listings yet",
    "dashboard.empty_hint": "Create your first cattle listing to start selling on PashuMarket.",
    "dashboard.new": "New Listing",
    "dashboard.list": "List your cattle",
    "dashboard.edit": "Edit",
    "dashboard.mark_sold": "Mark Sold",
    "dashboard.mark_available": "Mark Available",
    "dashboard.delete": "Delete",
    "dashboard.views": "views",
    "dashboard.interested": "interested",
    "dashboard.analytics": "Analytics",
    "dashboard.verified_seller": "Verified Seller",
    "location.use": "Use My Location",
    "location.set": "Location set",
    "location.sorted": "Sorted by distance · nearest first",
    "location.error": "Location unavailable",
    "location.km_away": "km away",
    "location.less_than_1km": "<1 km away",
    "map.title": "Cattle near your location",
    "map.switch_to_grid": "Switch to grid view",
    "map.coming_soon": "Interactive map coming soon — showing list view below",
    "sell.title": "List your cattle",
    "sell.edit_title": "Edit listing",
    "sell.publish": "Publish listing",
    "sell.update": "Update listing",
    "sell.publishing": "Publishing...",
    "sell.updating": "Updating...",
    "sell.success": "Listing published!",
    "sell.edit_success": "Listing updated!",
    "sell.redirect": "Redirecting to dashboard...",
    "install.title": "Install PashuMarket",
    "install.subtitle": "Add to home screen for quick access",
    "install.button": "Install",
    "nav.community": "Pashu-Charcha",
    "nav.community.short": "Community",
    "voice.tooltip": "Search by voice",
    "voice.activated": "Voice search activated",
    "voice.speaking": "Listening...",
    "voice.speak_now": "Bolo! Speak now",
    "voice.said": 'You said: "{text}"',
    "voice.not_supported": "Voice search is not supported on this browser",
    "voice.error": "Voice search failed. Please try again.",
    "voice.cow_found": "Cow listings found!",
    "voice.buffalo_found": "Buffalo listings found!",
    "voice.goat_found": "Goat listings found!",
    "voice.sheep_found": "Sheep listings found!",
    "ai.generate": "Generate with AI",
    "ai.generating": "Generating...",
    "ai.generated": "AI description generated!",
    "ai.description": "AI se description generate karein",
    "community.title": "Pashu-Charcha",
    "community.subtitle": "Apne sawaal, jaankari aur anubhav kisaan bhaiyon ke saath baanthein",
    "community.share_btn": "Post karein",
    "community.share_placeholder": "Kuch boliye... apna sawaal ya jaankari likhein",
    "community.post_shared": "Post shared!",
    "community.like": "Like",
    "community.comment": "Comment",
    "community.share": "Share",
    "community.empty": "Abhi tak koi post nahi hai. Kuch likhiye!",
    "community.loading": "Posts load ho rahe hain...",
    "inquiry.send": "Send Inquiry",
    "inquiry.sent": "Inquiry sent! Seller will contact you soon.",
    "inquiry.name": "Your name *",
    "inquiry.phone": "Phone number *",
    "inquiry.message": "Your message (optional)",
    "inquiry.report": "Report Listing",
    "inquiry.reported": "Reported",
    "inquiry.reported_msg": "Listing reported. We will review it shortly.",
    "inquiry.history": "Inquiry History",
    "inquiry.no_inquiries": "No inquiries yet",
    "inquiry.no_inquiries_hint": "Jab koi buyer inquiry bhejega, yahan dikhega",
    "inquiry.contact": "Contact {name}",
    "geo.sort": "Janwar Jo Mere Paas Hain",
    "geo.sort_active": "Paas Ke Janwar",
    "geo.sorted_by_distance": "Doori ke hisaab se: paas wale pehle",
    "dashboard.identity_verified": "Identity Verified",
    "dashboard.my_listings": "My Listings",
    "dashboard.inquiries": "Inquiries",
    "dashboard.title": "My Dashboard",
    "lang.en": "English",
    "lang.hi": "हिन्दी",
  },
  hi: {
    "app.name": "पशुMarket",
    "nav.sell": "पशु बेचें",
    "nav.dashboard": "डैशबोर्ड",
    "nav.search": "पशु, नस्ल या स्थान खोजें",
    "hero.title": "विश्वास के साथ पशु खरीदें और बेचें",
    "hero.subtitle": "वीडियो-फर्स्ट मार्केटप्लेस जो किसानों को सीधे जोड़ता है",
    "browse.title": "लोकप्रिय पशु श्रेणियां",
    "browse.label": "प्रकार के अनुसार देखें",
    "listings.featured": "विशेष लिस्टिंग",
    "listings.search": "खोज परिणाम",
    "listings.results_for": '"{query}" के परिणाम',
    "listings.category": "{category} लिस्टिंग",
    "listings.recent": "हाल ही में देखने के लिए तैयार पशु",
    "listings.description": "ये नमूना कार्ड पहले मार्केटप्लेस अनुभव को आकार देने में मदद करते हैं। डेटा लेयर तैयार होने पर इन्हें लाइव सेलर लिस्टिंग से बदलें।",
    "listings.empty": "कोई लिस्टिंग नहीं मिली",
    "listings.empty_hint": "कोई अलग खोज करें या ऊपर श्रेणियों में देखें।",
    "card.view_details": "विवरण देखें",
    "card.featured": "फीचर्ड",
    "card.sold": "बिक गया",
    "detail.back": "लिस्टिंग पर वापस जाएं",
    "detail.about": "इस पशु के बारे में",
    "detail.price": "कीमत",
    "detail.age": "आयु",
    "detail.milk_yield": "दूध उत्पादन",
    "detail.vaccination": "टीकाकरण",
    "detail.call_now": "अभी कॉल करें",
    "detail.whatsapp": "WhatsApp पूछताछ",
    "detail.share": "WhatsApp पर शेयर करें",
    "detail.verified_seller": "प्रमाणित विक्रेता",
    "detail.seller": "विक्रेता",
    "detail.views": "दृश्य",
    "detail.interested": "इच्छुक",
    "dashboard.subtitle": "अपनी पशु लिस्टिंग प्रबंधित करें — विवरण संपादित करें, बिक गया चिह्नित करें, या हटाएं।",
    "dashboard.empty": "अभी तक कोई लिस्टिंग नहीं",
    "dashboard.empty_hint": "पशुMarket पर बेचना शुरू करने के लिए अपनी पहली पशु लिस्टिंग बनाएं।",
    "dashboard.new": "नई लिस्टिंग",
    "dashboard.list": "अपने पशु सूचीबद्ध करें",
    "dashboard.edit": "संपादित करें",
    "dashboard.mark_sold": "बिक गया चिह्नित करें",
    "dashboard.mark_available": "उपलब्ध चिह्नित करें",
    "dashboard.delete": "हटाएं",
    "dashboard.views": "दृश्य",
    "dashboard.interested": "इच्छुक",
    "dashboard.analytics": "एनालिटिक्स",
    "dashboard.verified_seller": "प्रमाणित विक्रेता",
    "location.use": "मेरा स्थान उपयोग करें",
    "location.set": "स्थान सेट",
    "location.sorted": "दूरी के अनुसार क्रमबद्ध · निकटतम पहले",
    "location.error": "स्थान अनुपलब्ध",
    "location.km_away": "किमी दूर",
    "location.less_than_1km": "1 किमी से कम",
    "map.title": "आपके स्थान के निकट पशु",
    "map.switch_to_grid": "ग्रिड व्यू पर जाएं",
    "map.coming_soon": "इंटरैक्टिव मैप जल्द आ रहा है — नीचे सूची दृश्य दिखाया गया है",
    "sell.title": "अपने पशु सूचीबद्ध करें",
    "sell.edit_title": "लिस्टिंग संपादित करें",
    "sell.publish": "लिस्टिंग प्रकाशित करें",
    "sell.update": "लिस्टिंग अपडेट करें",
    "sell.publishing": "प्रकाशित हो रहा है...",
    "sell.updating": "अपडेट हो रहा है...",
    "sell.success": "लिस्टिंग प्रकाशित!",
    "sell.edit_success": "लिस्टिंग अपडेट!",
    "sell.redirect": "डैशबोर्ड पर रीडायरेक्ट...",
    "install.title": "पशुMarket इंस्टॉल करें",
    "install.subtitle": "त्वरित पहुंच के लिए होम स्क्रीन पर जोड़ें",
    "install.button": "इंस्टॉल करें",
    "nav.community": "पशु-चर्चा",
    "nav.community.short": "चर्चा",
    "voice.tooltip": "बोलकर खोजें",
    "voice.activated": "बोलकर खोज शुरू",
    "voice.speaking": "सुन रहे हैं...",
    "voice.speak_now": "बोलिए! अब बोलें",
    "voice.said": 'आपने कहा: "{text}"',
    "voice.not_supported": "यह ब्राउज़र बोलकर खोज सपोर्ट नहीं करता",
    "voice.error": "बोलकर खोज विफल। कृपया पुनः प्रयास करें।",
    "voice.cow_found": "गाय के लिस्टिंग मिले!",
    "voice.buffalo_found": "भैंस के लिस्टिंग मिले!",
    "voice.goat_found": "बकरी के लिस्टिंग मिले!",
    "voice.sheep_found": "भेड़ के लिस्टिंग मिले!",
    "ai.generate": "AI से विवरण बनाएं",
    "ai.generating": "बन रहा है...",
    "ai.generated": "AI विवरण तैयार हो गया!",
    "ai.description": "AI से विवरण जनरेट करें",
    "community.title": "पशु-चर्चा",
    "community.subtitle": "अपने सवाल, जानकारी और अनुभव किसान भाइयों के साथ बांटें",
    "community.share_btn": "पोस्ट करें",
    "community.share_placeholder": "कुछ बोलिए... अपना सवाल या जानकारी लिखें",
    "community.post_shared": "पोस्ट शेयर हो गया!",
    "community.like": "पसंद",
    "community.comment": "टिप्पणी",
    "community.share": "शेयर",
    "community.empty": "अभी तक कोई पोस्ट नहीं है। कुछ लिखिए!",
    "community.loading": "पोस्ट लोड हो रहे हैं...",
    "inquiry.send": "पूछताछ भेजें",
    "inquiry.sent": "पूछताछ भेज दी गई! विक्रेता जल्द संपर्क करेगा।",
    "inquiry.name": "आपका नाम *",
    "inquiry.phone": "फ़ोन नंबर *",
    "inquiry.message": "आपका संदेश (वैकल्पिक)",
    "inquiry.report": "रिपोर्ट करें",
    "inquiry.reported": "रिपोर्ट किया गया",
    "inquiry.reported_msg": "लिस्टिंग रिपोर्ट की गई। हम जल्द समीक्षा करेंगे।",
    "inquiry.history": "पूछताछ इतिहास",
    "inquiry.no_inquiries": "अभी तक कोई पूछताछ नहीं",
    "inquiry.no_inquiries_hint": "जब कोई खरीदार पूछताछ भेजेगा, यहाँ दिखेगा",
    "inquiry.contact": "{name} से संपर्क करें",
    "geo.sort": "जानवर जो मेरे पास हैं",
    "geo.sort_active": "पास के जानवर",
    "geo.sorted_by_distance": "दूरी के हिसाब से: पास वाले पहले",
    "dashboard.identity_verified": "पहचान प्रमाणित",
    "dashboard.my_listings": "मेरी लिस्टिंग",
    "dashboard.inquiries": "पूछताछ",
    "dashboard.title": "मेरा डैशबोर्ड",
    "lang.en": "English",
    "lang.hi": "हिन्दी",
  },
};

export function t(lang: Lang, key: string, params?: Record<string, string>): string {
  let val = dict[lang]?.[key] ?? dict.en[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      val = val.replace(`{${k}}`, v);
    }
  }
  return val;
}
