import {
  Beef,
  Cloud,
  Grid3x3,
  Droplets,
  Leaf,
  ShieldCheck,
  Sparkles,
  Truck,
  Video,
  Wheat,
} from "lucide-react";

import type { CattleCategory, CattleListing } from "@/models/cattle";

export const categories: CattleCategory[] = [
  {
    name: "Cow",
    description: "Gir, Sahiwal, Jersey",
    icon: Leaf,
  },
  {
    name: "Buffalo",
    description: "Murrah, Jaffarabadi",
    icon: Droplets,
  },
  {
    name: "Goat",
    description: "Beetal, Jamunapari",
    icon: Beef,
  },
  {
    name: "Sheep",
    description: "Nali, Dorper",
    icon: Cloud,
  },
  {
    name: "Other",
    description: "Calves, bulls, mixed stock",
    icon: Grid3x3,
  },
];

export const cattleListings: CattleListing[] = [
  {
    id: "g1",
    title: "Gir Cow – High Yield",
    category: "Cow",
    breed: "Gir Cow",
    location: "Karnal, Haryana",
    price: 55000,
    mediaLabel: "Video preview available",
    statusLabel: "High milk yield",
    featured: true,
    sellerName: "Ramesh Singh",
    description: "A healthy Gir cow with excellent milk production. Calm temperament, ideal for dairy farming.",
    age: "4 years",
    milkYield: "12 litres/day",
    vaccinationStatus: "Fully vaccinated (HA, BQ, Brucellosis)",
    latitude: 29.6857,
    longitude: 76.9905,
    views: 245,
    interestCount: 23,
  },
  {
    id: "b1",
    title: "Murrah Buffalo – Premium Breed",
    category: "Buffalo",
    breed: "Murrah Buffalo",
    location: "Ludhiana, Punjab",
    price: 72000,
    mediaLabel: "Seller video attached",
    statusLabel: "Pregnancy checked",
    featured: true,
    sellerName: "Gurpreet Kaur",
    description: "Premium Murrah buffalo. High fat content milk. Pregnancy verified by local vet.",
    age: "5 years",
    milkYield: "8 litres/day (6% fat)",
    vaccinationStatus: "Vaccinated + dewormed",
    latitude: 30.901,
    longitude: 75.8573,
    views: 189,
    interestCount: 15,
  },
  {
    id: "g2",
    title: "Jamunapari Goat",
    category: "Goat",
    breed: "Jamunapari Goat",
    location: "Agra, Uttar Pradesh",
    price: 18000,
    mediaLabel: "Short reel ready",
    statusLabel: "Healthy herd",
    featured: false,
    sellerName: "Vikram Yadav",
    description: "Strong Jamunapari buck. Excellent for breeding programmes. Active and disease-free.",
    age: "2 years",
    milkYield: "3 litres/day",
    vaccinationStatus: "Primary course complete",
    latitude: 27.1767,
    longitude: 78.0081,
    views: 76,
    interestCount: 8,
  },
  {
    id: "s1",
    title: "Dorper Sheep – Ready Stock",
    category: "Sheep",
    breed: "Dorper Sheep",
    location: "Jaipur, Rajasthan",
    price: 24000,
    mediaLabel: "Walkaround clip",
    statusLabel: "Vaccinated recently",
    featured: false,
    sellerName: "Mohammed Rafiq",
    description: "Three healthy Dorper sheep. Hardy breed suited for arid climates. Ready for sale.",
    age: "1.5 years",
    milkYield: "N/A",
    vaccinationStatus: "Recent PPR + ET vaccination",
    latitude: 26.9124,
    longitude: 75.7873,
    views: 112,
    interestCount: 10,
  },
  {
    id: "o1",
    title: "HF Cross Heifer",
    category: "Other",
    breed: "HF Cross Heifer",
    location: "Indore, Madhya Pradesh",
    price: 46000,
    mediaLabel: "Marketplace reel",
    statusLabel: "Farm verified",
    featured: true,
    sellerName: "Priya Sharma",
    description: "HF cross-breed heifer. Good conformation, excellent potential for dairy. Raised on farm.",
    age: "18 months",
    milkYield: "Will calve in 3 months",
    vaccinationStatus: "All age-appropriate vaccines given",
    latitude: 22.7196,
    longitude: 75.8577,
    views: 156,
    interestCount: 14,
  },
  {
    id: "g3",
    title: "Sahiwal Cow – Pure Breed",
    category: "Cow",
    breed: "Sahiwal Cow",
    location: "Karnal, Haryana",
    price: 62000,
    mediaLabel: "Video attached",
    statusLabel: "High butterfat",
    featured: false,
    sellerName: "Ramesh Singh",
    description: "Pure Sahiwal cow known for high butterfat content. Very docile and easy to manage.",
    age: "3 years",
    milkYield: "10 litres/day (5% fat)",
    vaccinationStatus: "Fully vaccinated",
    latitude: 29.6914,
    longitude: 76.995,
    views: 87,
    interestCount: 5,
  },
  {
    id: "g4",
    title: "Jersey Cross Cow",
    category: "Cow",
    breed: "Jersey Cross",
    location: "Karnal, Haryana",
    price: 48000,
    mediaLabel: "Walkaround clip",
    statusLabel: "Excellent health",
    featured: false,
    sellerName: "Ramesh Singh",
    description: "Jersey cross-breed cow with excellent health record. Ideal for small dairy farms.",
    age: "2.5 years",
    milkYield: "14 litres/day",
    vaccinationStatus: "All vaccines up to date",
    latitude: 29.6805,
    longitude: 76.9832,
    views: 134,
    interestCount: 12,
  },
  {
    id: "g5",
    title: "Tharparkar Cow – Native Breed",
    category: "Cow",
    breed: "Tharparkar Cow",
    location: "Karnal, Haryana",
    price: 52000,
    mediaLabel: "Short reel ready",
    statusLabel: "Drought resistant",
    featured: true,
    sellerName: "Ramesh Singh",
    description: "Hardy Tharparkar cow suited for arid regions. Excellent heat tolerance and disease resistance.",
    age: "4 years",
    milkYield: "8 litres/day",
    vaccinationStatus: "Vaccinated + dewormed",
    latitude: 29.6933,
    longitude: 76.9889,
    views: 210,
    interestCount: 18,
  },
];

export const trustHighlights = [
  { label: "Verified sellers", icon: ShieldCheck },
  { label: "Video listings", icon: Video },
  { label: "Fast local delivery", icon: Truck },
  { label: "Breed insights", icon: Sparkles },
  { label: "Fair pricing support", icon: Wheat },
];
